# Generated by Django 3.1.2 on 2020-10-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cars', '0002_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('', ''), ('mechanics', 'mechanics'), ('automatic', 'automatic'), ('robot', 'robot')], max_length=128, verbose_name='Коробка передачи'),
        ),
    ]
