# Generated by Django 3.1.2 on 2020-10-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cars', '0003_auto_20201028_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('', ''), ('me', 'mechanics'), ('au', 'automatic'), ('ro', 'robot')], max_length=128, verbose_name='Коробка передачи'),
        ),
    ]
