# Generated by Django 3.1.2 on 2020-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cars', '0004_auto_20201028_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[(0, ''), (1, 'mechanics'), (2, 'automatic'), (3, 'robot')], default=0, verbose_name='Коробка передачи'),
        ),
    ]
